In [1]:
import pandas as pd
import bamboolib as bam
cars_data = pd.read_csv("cars.csv")
cars_data

,name,sports_car,suv,wagon,minivan,pickup,all_wheel,rear_wheel,Price,Dealer_Cost,Engine_size,cylenders,horsepower,city_miles_per_galloon,highway_miles_per_Gallon,weight,base_wheeel,length,width
0,Chevrolet Aveo 4dr,False,False,False,False,False,False,False,11690,10965,1.6,4,103,28.0,34.0,2370.0,98.0,167.0,66.0
1,Chevrolet Aveo LS 4dr hatch,False,False,False,False,False,False,False,12585,11802,1.6,4,103,28.0,34.0,2348.0,98.0,153.0,66.0
2,Chevrolet Cavalier 2dr,False,False,False,False,False,False,False,14610,13697,2.2,4,140,26.0,37.0,2617.0,104.0,183.0,69.0
3,Chevrolet Cavalier 4dr,False,False,False,False,False,False,False,14810,13884,2.2,4,140,26.0,37.0,2676.0,104.0,183.0,68.0
4,Chevrolet Cavalier LS 2dr,False,False,False,False,False,False,False,16385,15357,2.2,4,140,26.0,37.0,2617.0,104.0,183.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Nissan Titan King Cab XE,False,False,False,False,True,True,False,26650,24926,5.6,8,305,14.0,18.0,5287.0,140.0,NaN,NaN
424,Subaru Baja,False,False,False,False,True,True,False,24520,22304,2.5,4,165,21.0,28.0,3485.0,104.0,NaN,NaN
425,Toyota Tacoma,False,False,False,False,True,False,True,12800,11879,2.4,4,142,22.0,27.0,2750.0,103.0,NaN,NaN
426,Toyota Tundra Regular Cab V6,False,False,False,False,True,False,True,16495,14978,3.4,6,190,16.0,20.0,3925.0,128.0,NaN,NaN
427,Toyota Tundra Access Cab V6 SR5,False,False,False,False,True,True,False,25935,23520,3.4,6,190,14.0,17.0,4435.0,128.0,NaN,NaN